server:
  port: 8961

mapper:
  use-simple-type: true

#MyBatis
mybatis:
  typeAliasesPackage: com.yyh.ssmspringboot.entity

#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      connectionProperties: druid.stat.slowSqlMillis=5000
      platform: mysql

swagger:
  enabled: true
  authorization:
    key-name: Authorization
  docket:
    pc:
      title: ssm
      description: ssm 框架搭建
      version: 1.0
      base-package: com.yyh.ssmspringboot.controller
      basePath: /user/**
      contact:
        name: yyh
        email: 2728142607@qq.com
        url: https://github.com/youtehub

logging:
  level:
    com.liaoin.reclaim.mybatis: trace